name: Pipeline CI/CD

on:    # Trigger conditions for the pipeline
  push:
    branches: [ main ]    # Run pipeline when code is pushed to main branch
  pull_request:
    branches: [ main ]    # Run pipeline when a PR is made to main branch

jobs:  
  build_and_test:
    name: Building and Testing
    uses: ./.github/workflows/1build-and-test.yml    # References the combined build and test workflow

  analysis:
    name: Analysing    # Performs code quality analysis with SonarCloud
    needs: test
    uses: ./.github/workflows/3sonarqube.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Authentication token for SonarCloud to be found in GitHub Secrets

  containerization:
    name: Containerizing    # Builds and pushes frontend and backend Docker images
    needs: analysis
    uses: ./.github/workflows/4docker.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}