name: SonarQube Analysis

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download backend coverage report
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage-report
          path: back/target/site/jacoco/

      - name: Download frontend coverage report
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage-report
          path: front/coverage/bobapp/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download backend classes
        uses: actions/download-artifact@v4
        with:
          name: backend-classes
          path: back/target/classes

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=ocrp10analysis 
            -Dsonar.organization=adthomdev
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=back/src/main/java,front/src
            -Dsonar.tests=back/src/test/java
            -Dsonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*Test.java
            -Dsonar.java.binaries=back/target/classes
            -Dsonar.java.coveragePlugin=jacoco
            -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
            -Dsonar.typescript.lcov.reportPaths=front/coverage/bobapp/lcov.info
            -Dsonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.inclusions=**/*.java,**/*.js,**/*.ts,**/*.html,**/*.css,**/*.scss
            -Dsonar.exclusions=front/node_modules/**,front/dist/**,front/coverage/**,front/src/test.ts,front/src/environments/*.ts,**/*.spec.ts,**/*.test.ts,**/*.min.js
            -Dsonar.typescript.file.suffixes=.ts,.tsx
            -Dsonar.javascript.file.suffixes=.js,.jsx
