name: SonarQube Analysis

on:
  workflow_run:
    workflows: ["Tests (Junit/JaCoCo and Jasmine/Karma)"]
    types:
      - completed

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: [backend_tests, frontend_tests]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Download backend coverage report
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage-report
          path: back/target/site/jacoco/

      - name: Download frontend coverage report
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage-report
          path: front/coverage/bobapp/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ocrp10analysis
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.junit.reportsPath=back/target/surefire-reports
            -Dsonar.jacoco.reportsPath=back/target/site/jacoco/jacoco.xml
            -Dsonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
