name: Build

on:
  push:
    branches:
      - develop-front
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./front

      - name: Build Angular app
        run: npm run build --prod
        working-directory: ./front